### ISSUE TITLE
Errors while running ./waf

### ISSUE THREAD

**Issue by Divyalanka123** [CSVNetLab/PA-GPSR#1]
Dear Sir,
There are some errors while running ./waf
![gpsr](https://user-images.githubusercontent.com/46359342/63743481-fbc4e280-c8b9-11e9-9bef-d9f26d5549fd.png)

**Comment by CSVNetLab** [comment]
Hello Divya,

The code is working fine for ns3 v3.23 only. You're trying to install it on ns-3.27. Please, try to use it with the ns3 v3.23 (http://www.nsnam.org/release/ns-allinone-3.23.tar.bz2). I had the same error while running it on ns3 v3.29. I did fix it.  I'll push the updated version soon. In this mean time, please, use the ns3.23.
